### ISSUE TITLE
Pravice na bazi za javnost

### ISSUE THREAD

**Issue by PirnovarA** [larajagodnik/Avtohisa#2]
Za uporabo aplikacije bo potrebno še uporabniku "javnost" dodati nekatere pravice (sigurno SELECT, verjetno INSERT; kot ste si zamislili aplikacijo). Se ne mudi, samo da ne pozabite, ker ste ze zaceli z izdelavo baze.

**Comment by JanSifrer** [comment]
Hvala za obvestilo. Sem dodal samo pravico `SELECT`, ker še ne vemo čisto točno katere pravice bo imel uporabnik `javnost`.
