### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by JanSifrer** [larajagodnik/Avtohisa#3]
Pojavila se nam je manjša težava, in sicer hoteli smo narediti, da bi se aplikacija poganjala tudi z Binder-jem, ampak smo naleteli na neki problem. Ko poženemo Binder nam izpiše `error`, da nas je spletni mesto prevečkrat preusmerilo... 
In Vas prosimo za pomoč, kako bi se najlažje to napako odpravilo. :)

**Comment by jaanos** [comment]
Ne vem, če je res v tem problem, a načeloma bi morala mapa s konfiguracijo za Binder morala biti poimenovana `binder`, torej z malo začetnico. Najlažje bo, če jo najprej preimenujete v nekaj drugega, naredite commit, nato pa spet preimenujete v `binder` in znova naredite commit in push.

**Comment by JanSifrer** [comment]
Ahaa opala, najlepša Vam hvala za odgovor. Sedaj deluje!

**Comment by JanSifrer** [comment]
Pozdravljeni, 
ponovno imava manjšo težavo z Binderjem, kajti ko ga poiskušava zagnati nama napiše `error 500`. Tako da bi prosil za kakšen nasvet, kako popraviti to zadevo.
Hvala!

**Comment by jaanos** [comment]
Problem je tukaj:
https://github.com/larajagodnik/Avtohisa/blob/54c78c317b9d2680afbae88468632d3674c9058c/aplikacija.py#L6
Če namesto `conf_baza` (ki ga nimata na repozitoriju) uvozita `auth_public`, bi moralo delovati.

**Comment by JanSifrer** [comment]
Najlepša Vam hvala! 
Zadeva sedaj deluje! 
Lp, Jan

**Comment by JanSifrer** [comment]
Pozdravljeni,
sedaj pa imava še en drug problem. In sicer v Binderju nama ne delajo gumbi za prijavo in registracijo, ter tudi filtriranje po tabeli ne deluje (kar vse normalno deluje, če zadevo poženeš preko računalnika...). 
Imate mogoče tudi za ta problem kakšno enostavno rešitev? :)

**Comment by jaanos** [comment]
Poskrbita, da se vse poti v `redirect`-ih in v predlogah (atributi `href`, `src` in `action`) začnejo s spremenljivko `ROOT` namesto z `/`. V 83e945f27f76a13a2879b4a972f365c7b4a608f9 gresta v pravo smer (v zadnjih dveh commitih sta to odstranila), samo še pri vseh drugih primerih bo treba narediti enako.

**Comment by JanSifrer** [comment]
Ahaa najlepša Vam hvala! 
Sva sedaj popravila in zadeva deluje!
