### ISSUE TITLE
base namesto iframe

### ISSUE THREAD

**Issue by JanSifrer** [larajagodnik/Avtohisa#4]
Pozdravljeni, 
v datoteki [zacetna.html](https://github.com/larajagodnik/Avtohisa/blob/master/views/zacetna.html), sem poskušal uporabiti ukaz `{{!base}}` namesto `iframa`, vendar mi javlja napako: 
* NameError("name 'base' is not defined",)
Tako da bi prosil za pomoč, kako naj odpravim to napako.

**Comment by jaanos** [comment]
Problem je v tem, da začetna stran (pot `/`) uporablja predlogo `zacetna.html`, ki pa jo je mogoče zaradi uporabe `{{!base}}` uporabiti samo z `rebase` - na `http://localhost:8080/avto/vsi` deluje tako, kot mora.

Za začetno stran naredite torej novo predlogo (ki lahko, tako kot druge, uporabi `rebase` iz `zacetna.html`) - lahko pa enostavno naredite preusmeritev (`redirect`) na `/avto/vsi`.

Mimogrede, predlagal bi, da CSS in JavaScript premaknete iz `zacetna.html` v namenske statične datoteke - sintaksa obeh namreč uporablja zavite oklepaje, zaradi česar lahko pride do konflikta z jezikom za predloge.
